# 베이스 이미지로 Python 3.9 사용
FROM python:3.12

# 작업 디렉터리를 설정
WORKDIR /app

# 필요 패키지 목록 복사
COPY requirements.txt /app/

# 패키지 설치
RUN pip install --no-cache-dir -r requirements.txt

# 소스 코드 복사
COPY . /app/

# 포트를 노출
EXPOSE 8000

# Django 서버 실행 명령
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000","--noreload"]