services:
  node:
    env_file: 
      - .env
    build: .
    image: nmm_bot
    # container_name: nmm_django
    ports:
      - "8100:3100"
    networks:
      - jungle_network
    volumes:
      - /home/ubuntu/db/pdfs:/app/pdfs
networks:
  jungle_network:
    external: true
    driver: bridge